# Generated by Django 3.1.4 on 2021-01-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='Content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='Title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.CharField(default='https://cdn.pixabay.com/photo/2014/04/13/20/49/cat-323262_960_720.jpg', max_length=1000),
        ),
    ]
